# Generated by Django 2.1.5 on 2019-01-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('onderwerp', models.CharField(max_length=250)),
                ('bericht', models.TextField()),
            ],
        ),
    ]
